name: qinglong_app
description: base on https://github.com/whyour/qinglong
publish_to: 'none'
version: 3.0.0+300

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.10.1"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.1.1
  shared_preferences: ^2.0.15
  synchronized: ^3.0.0+3
  back_button_interceptor: ^6.0.2
  flutter_slidable: ^2.0.0
  dio: ^4.0.6
  dio_log: ^2.0.4
  json_conversion_annotation: ^0.0.4
  logger: ^1.1.0
  intl: ^0.17.0
  get_it: ^7.2.0
  highlight: ^0.7.0
  drag_and_drop_lists: ^0.3.3
  fluttertoast: ^8.1.1
  move_to_background: ^1.0.2
  flip_card: ^0.6.0
  package_info_plus: ^3.0.2
  url_launcher: ^6.1.7
  flutter_colorpicker: ^1.0.3
  flutter_animator: ^3.2.2
  local_auth: ^2.1.2
  share_plus: ^6.3.0
  pretty_dio_logger: ^1.1.1
  icloud_storage: ^1.0.0
  path_provider: ^2.0.11
  date_format: ^2.0.7
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.2.2
  flutter_dynamic_icon: ^2.1.0
  file_picker: ^5.2.2
  convex_bottom_bar: ^3.1.0+1
  custom_sliding_segmented_control: ^1.7.3
  timeago: ^3.3.0
  launch_review: ^3.0.1
  flutter_scroll_to_top: ^2.3.0
  json_table: ^2.0.1
  extended_text: ^9.1.2
  lottie: ^2.0.0
  quick_actions: ^1.0.1
  webview_flutter: 3.0.4
  flutter_keyboard_visibility: ^5.4.0
  permission_handler: ^10.2.0
  flutter_displaymode: ^0.4.1
  loading_animation_widget: ^1.2.0+3
  get: ^4.6.5
  timezone: ^0.9.0
  flutter_native_splash: ^2.2.10+1



dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  change_app_package_name: ^1.1.0
  #  flutter_app_name: ^0.1.1

  build_runner: ^2.1.7
  json_conversion: ^0.0.4
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/scan.json
    - assets/images/
    - assets/codemirror.html
flutter_app_name:
  name: "青龙面板"

flutter_icons:
  image_path_android: "assets/images/ql.png"
  image_path_ios: "assets/images/ql_white.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"


flutter_native_splash:

  color: "#ffffff"
  branding_mode: bottom
  color_dark: "#000000"
  fullscreen: false
